project_name: goptuna
env:
  - GO111MODULE=auto
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/main.go
    binary: goptuna
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.revision={{.ShortCommit}}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      386: i386
      amd64: x86_64
    format: zip
release:
  prerelease: auto
