name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node v18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: go install golang.org/x/tools/cmd/stringer@latest
      - run: |
          cd dashboard
          npm install
          npm run build:prd
          git checkout package-lock.json  # Avoid https://github.com/c-bata/goptuna/runs/2420513033

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
