name: Run examples
on:
  pull_request:
    branches:
      - benchmark-**
jobs:
  examples:
    name: Run kurobako's benchmark
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Download kurobako CLI
        run: |
          curl -L https://github.com/sile/kurobako/releases/download/0.1.4/kurobako-0.1.4.linux-amd64 -o kurobako
          chmod +x kurobako
          ./kurobako -h

      - name: Run sigopt/evalset/Ackley Benchmark
        run: |
          RANDOM_SOLVER=$(kurobako solver random)
          GOPTUNA_SOLVER=$(kurobako solver command go run _benchmarks/kurobako-solver/main.go)
          ACKLEY_PROBLEM=$(kurobako problem sigopt --dim 5 ackley)
          kurobako studies --solvers $RANDOM_SOLVER $GOPTUNA_SOLVER --problems $ACKLEY_PROBLEM --repeats 100 --budget 100 | kurobako run --parallelism 4 > result.json
          cat result.json | kurobako report

      # TODO: then upload an image of `kurobako plot curve` as the comment on PR. It require gnuplot.
