name: typescript-checks
on:
  pull_request:
    paths:
      - '.github/workflows/typescript-checks.yml'
      - 'dashboard/package.json'
      - '**.ts'
      - '**.tsx'
jobs:
  lint:
    name: Lint checking on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: |
          cd dashboard
          npm install
          npm run lint
  build:
    name: JS build check
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: |
          cd dashboard
          npm install
          npm run build:dev
          npm run build:prd

